#version 460 core
layout(local_size_x = 1, local_size_y = 1) in;
layout(rgba32f, binding = 0) uniform image2D img_output;
layout(rgba32f, binding = 1) uniform image2D img_output_buffer;


void main ()
{
	// get the index in the global work group (= x,y position)
	ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);

	vec4 color = imageLoad(img_output_buffer, pixel_coords) * 0.95;


	vec4 pixel = vec4(color.r, color.g, color.b, 1.0);

	imageStore(img_output, pixel_coords, pixel);
};